version: '3'

services:
  crawler:
    build: 
      network: host
      context: ./crawler/
    environment:
      - STORAGE_SERVICE_NAME=${STORAGE_SERVICE_NAME}
      - STORAGE_SERVICE_PORT=${STORAGE_SERVICE_PORT}
      - CRAWLER_SOURCE_ADDRESS=${CRAWLER_SOURCE_ADDRESS}
    volumes:
      - ./crawler/app:/crawler/app/:rw
    entrypoint: "python3 crawler.py"
    container_name: ${CRAWLER_SERVICE_NAME}
  storage:
    build:
      network: host
      context: ./storage/
      args: 
      - STORAGE_SERVICE_PORT=${STORAGE_SERVICE_PORT}
    ports:
      - ${STORAGE_SERVICE_PORT}:${STORAGE_SERVICE_PORT}
    environment:
      - FLASK_APP=/storage/app/storage.py
      - STORAGE_SERVICE_PORT=${STORAGE_SERVICE_PORT}
      - DB_SERVICE_NAME=${DB_SERVICE_NAME}
      - DB_SERVICE_PORT=${DB_SERVICE_PORT}
    volumes:
      - ./storage/app:/storage/app:rw
    container_name: ${STORAGE_SERVICE_NAME}
    entrypoint: "flask run --host 0.0.0.0 --port ${STORAGE_SERVICE_PORT}"  
  db:
    image: redis:latest
    ports:
      - ${DB_SERVICE_PORT}:${DB_SERVICE_PORT}
    volumes:
      - db_data:/data:rw
    container_name: ${DB_SERVICE_NAME}
volumes:
    db_data: {}